/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5p2_juanmembreño;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author usuario
 */
public class mainlab5 extends javax.swing.JFrame {

    /**
     * Creates new form mainlab5
     */
    public mainlab5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_jugadores = new javax.swing.JDialog();
        jnumerojug = new javax.swing.JTextField();
        jcantp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        janos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        japellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jnacionalidad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jedad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jd_entrenadores = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        eapellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        enacionalidad = new javax.swing.JTextField();
        eedad = new javax.swing.JTextField();
        enombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eanosc = new javax.swing.JTextField();
        ecantcopas = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jd_preparadores = new javax.swing.JDialog();
        papellido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pnacionalidad = new javax.swing.JTextField();
        pedad = new javax.swing.JTextField();
        pnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        panosc = new javax.swing.JTextField();
        pespecialidad = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jd_psicologos = new javax.swing.JDialog();
        psapellido = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        psnacionalidad = new javax.swing.JTextField();
        psedad = new javax.swing.JTextField();
        psnombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        psid = new javax.swing.JTextField();
        pstitulo = new javax.swing.JTextField();
        psespecialidad = new javax.swing.JTextField();
        psinformes = new javax.swing.JTextField();
        psatendidos = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jd_agregar = new javax.swing.JDialog();
        jLabel35 = new javax.swing.JLabel();
        bj = new javax.swing.JRadioButton();
        be = new javax.swing.JRadioButton();
        bp = new javax.swing.JRadioButton();
        bps = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jtree = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jlist = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_personas = new javax.swing.JList<>();
        popupjl = new javax.swing.JPopupMenu();
        modificar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jLabel11.setText("cantidad de partidos jugados");

        jLabel17.setText("Años de contrato");

        jnombre.setText(" ");

        jLabel5.setText("Jugadores");

        jLabel8.setText("Nombre");

        jLabel9.setText("Apellido");

        jLabel18.setText("Nacionalidad");

        jLabel19.setText("edad");

        jLabel20.setText("numero de jugador");

        jButton2.setText("Finalizar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_jugadoresLayout = new javax.swing.GroupLayout(jd_jugadores.getContentPane());
        jd_jugadores.getContentPane().setLayout(jd_jugadoresLayout);
        jd_jugadoresLayout.setHorizontalGroup(
            jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(32, 32, 32)
                                .addComponent(jnacionalidad))
                            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(japellido, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(76, 76, 76)
                                .addComponent(jedad))
                            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                                .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(27, 27, 27)
                                        .addComponent(jnumerojug))
                                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(33, 33, 33)
                                        .addComponent(jcantp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(janos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel5)))
                .addGap(135, 135, 135)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jd_jugadoresLayout.setVerticalGroup(
            jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_jugadoresLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5)
                        .addGap(45, 45, 45)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(japellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jnumerojug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jcantp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(janos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jLabel1.setText("Entrenadores");

        jLabel10.setText("Nombre");

        jLabel12.setText("Apellido");

        jLabel21.setText("Nacionalidad");

        jLabel22.setText("edad");

        enombre.setText(" ");

        jLabel2.setText("Años de contrato");

        jLabel4.setText("Cantidad de copas ganadas");

        ecantcopas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecantcopasActionPerformed(evt);
            }
        });

        jButton3.setText("Fianlizar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_entrenadoresLayout = new javax.swing.GroupLayout(jd_entrenadores.getContentPane());
        jd_entrenadores.getContentPane().setLayout(jd_entrenadoresLayout);
        jd_entrenadoresLayout.setHorizontalGroup(
            jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1))
                    .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(76, 76, 76)
                                .addComponent(eedad, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(69, 69, 69)
                                .addComponent(enombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel12))
                                .addGap(32, 32, 32)
                                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(eanosc, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(ecantcopas, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(320, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_entrenadoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jd_entrenadoresLayout.setVerticalGroup(
            jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(enombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(eapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(enacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(eedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eanosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ecantcopas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jLabel13.setText("Nombre");

        jLabel14.setText("Apellido");

        jLabel23.setText("Nacionalidad");

        jLabel24.setText("edad");

        pnombre.setText(" ");

        jLabel3.setText("Preparadores");

        Id.setText("Id");

        jLabel7.setText("Años de contrato");

        jLabel25.setText("Especialidad");

        jButton4.setText("Finalizar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_preparadoresLayout = new javax.swing.GroupLayout(jd_preparadores.getContentPane());
        jd_preparadores.getContentPane().setLayout(jd_preparadoresLayout);
        jd_preparadoresLayout.setHorizontalGroup(
            jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_preparadoresLayout.createSequentialGroup()
                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_preparadoresLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_preparadoresLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(30, 30, 30)
                                .addComponent(papellido, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_preparadoresLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(52, 52, 52)
                                .addComponent(pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_preparadoresLayout.createSequentialGroup()
                                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(Id)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel25))
                                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_preparadoresLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pedad, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(pnacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(pid)
                                            .addComponent(panosc)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_preparadoresLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(pespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_preparadoresLayout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel3)))
                .addGap(169, 169, 169))
        );
        jd_preparadoresLayout.setVerticalGroup(
            jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_preparadoresLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_preparadoresLayout.createSequentialGroup()
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(papellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(pnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_preparadoresLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(pedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_preparadoresLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id)
                            .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7))
                    .addComponent(panosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(pespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jLabel26.setText("Nombre");

        jLabel27.setText("Apellido");

        jLabel28.setText("Nacionalidad");

        jLabel29.setText("edad");

        psnombre.setText(" ");

        jLabel6.setText("Id");

        jLabel30.setText("Titulo universitario");

        jLabel31.setText("Especialidad");

        jLabel32.setText("Cantidad informes generados");

        jLabel33.setText("# jugadores atendidos");

        psid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psidActionPerformed(evt);
            }
        });

        jLabel34.setText("Psicologos");

        jButton5.setText("Finalizar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_psicologosLayout = new javax.swing.GroupLayout(jd_psicologos.getContentPane());
        jd_psicologos.getContentPane().setLayout(jd_psicologosLayout);
        jd_psicologosLayout.setHorizontalGroup(
            jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_psicologosLayout.createSequentialGroup()
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_psicologosLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_psicologosLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(36, 36, 36)
                                .addComponent(psatendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jd_psicologosLayout.createSequentialGroup()
                                    .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel26))
                                    .addGap(29, 29, 29)
                                    .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(psnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(psedad, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(psnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(psapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_psicologosLayout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addGap(28, 28, 28)
                                    .addComponent(psespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jd_psicologosLayout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addGap(18, 18, 18)
                                    .addComponent(pstitulo))
                                .addGroup(jd_psicologosLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(38, 38, 38)
                                    .addComponent(psid, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_psicologosLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(psinformes, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_psicologosLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel34)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jd_psicologosLayout.setVerticalGroup(
            jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_psicologosLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel34)
                .addGap(74, 74, 74)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(psapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(psnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(psedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(psid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(pstitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(psespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(psinformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(psatendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_psicologosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        jLabel35.setText("Selecione su cargo");

        buttonGroup2.add(bj);
        bj.setText("Jugador");

        buttonGroup2.add(be);
        be.setText("Entrenador");

        buttonGroup2.add(bp);
        bp.setText("Preparador");

        buttonGroup2.add(bps);
        bps.setText("Psicologo");

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarLayout = new javax.swing.GroupLayout(jd_agregar.getContentPane());
        jd_agregar.getContentPane().setLayout(jd_agregarLayout);
        jd_agregarLayout.setHorizontalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel35))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(bj)
                        .addGap(38, 38, 38)
                        .addComponent(be)
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addComponent(bp)
                                .addGap(49, 49, 49)
                                .addComponent(bps)))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jd_agregarLayout.setVerticalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel35)
                .addGap(68, 68, 68)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bj)
                    .addComponent(be)
                    .addComponent(bp)
                    .addComponent(bps))
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Equipo");
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jtreeLayout = new javax.swing.GroupLayout(jtree.getContentPane());
        jtree.getContentPane().setLayout(jtreeLayout);
        jtreeLayout.setHorizontalGroup(
            jtreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtreeLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jtreeLayout.setVerticalGroup(
            jtreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtreeLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jl_personas.setModel(new DefaultListModel());
        jl_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_personas);

        javax.swing.GroupLayout jlistLayout = new javax.swing.GroupLayout(jlist.getContentPane());
        jlist.getContentPane().setLayout(jlistLayout);
        jlistLayout.setHorizontalGroup(
            jlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlistLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jlistLayout.setVerticalGroup(
            jlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlistLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        modificar.setText("modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        popupjl.add(modificar);

        eliminar.setText("eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        popupjl.add(eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu8.setText("Inicio");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Agregar");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenuBar3.add(jMenu8);

        jMenu9.setText("Administrar");

        jMenuItem3.setText("Ver Jtree");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem3);

        jMenuItem4.setText("Ver Jlist");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem4);

        jMenuBar3.add(jMenu9);
        jMenuBar3.add(jMenu1);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        abreagregar();
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (bj.isSelected()) {
            abrejug();

        } else if (be.isSelected()) {
            abreen();
        } else if (bp.isSelected()) {
            abrepre();
        } else if (bps.isSelected()) {
            abreps();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        abreagregar();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        DefaultListModel modelo
                = (DefaultListModel) jl_personas.getModel();
        modelo.addElement(new jugadores(jnombre.getText(), japellido.getText(), jnacionalidad.getText(), Integer.parseInt(jedad.getText()), Integer.parseInt(jnumerojug.getText()), Integer.parseInt(janos.getText())));
        jl_personas.setModel(modelo);
        
        
        //jtre
       // DefaultTreeModel m= (DefaultTreeModel) jtree.getModel();
       // DefaultM
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void ecantcopasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecantcopasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecantcopasActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        DefaultListModel modelo
                = (DefaultListModel) jl_personas.getModel();

        modelo.addElement(new entrenadores(enombre.getText(), eapellido.getText(), enacionalidad.getText(), Integer.parseInt(eedad.getText()), Integer.parseInt(eanosc.getText()), Integer.parseInt(ecantcopas.getText())));
        jl_personas.setModel(modelo);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        DefaultListModel modelo
                = (DefaultListModel) jl_personas.getModel();

        modelo.addElement(new preparadores(pnombre.getText(), papellido.getText(), pnacionalidad.getText(), Integer.parseInt(pedad.getText()), Integer.parseInt(pid.getText()), Integer.parseInt(panosc.getText()), pespecialidad.getText()));
        jl_personas.setModel(modelo);
    }//GEN-LAST:event_jButton4MouseClicked

    private void psidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psidActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        DefaultListModel modelo
                = (DefaultListModel) jl_personas.getModel();

        modelo.addElement(new psicologos(psnombre.getText(), psapellido.getText(), psnacionalidad.getText(), Integer.parseInt(psedad.getText()), pstitulo.getText(), Integer.parseInt(psid.getText()), psespecialidad.getText()));
        jl_personas.setModel(modelo);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        abrejl();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jl_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personasMouseClicked
       if(jl_personas.getSelectedIndex()>=0){
           if(evt.isMetaDown()){
               popupjl.show(evt.getComponent(),evt.getX(),evt.getY());
           }
       }
    }//GEN-LAST:event_jl_personasMouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if(jl_personas.getSelectedIndex()>=0){
            DefaultListModel modelolista=(DefaultListModel) jl_personas.getModel();
            ((jugadores) modelolista.get(jl_personas.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("Nombre"));
            
            modelolista=(DefaultListModel) jl_personas.getModel();
            ((jugadores) modelolista.get(jl_personas.getSelectedIndex())).setApellido(JOptionPane.showInputDialog("Apellido"));
            
            modelolista=(DefaultListModel) jl_personas.getModel();
            ((jugadores) modelolista.get(jl_personas.getSelectedIndex())).setApellido(JOptionPane.showInputDialog("nacionalidad"));
            
            jl_personas.setModel(modelolista);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
            if(jl_personas.getSelectedIndex()>=0){
              DefaultListModel modelolista=(DefaultListModel) jl_personas.getModel();
              modelolista.remove(jl_personas.getSelectedIndex());
              jl_personas.setModel(modelolista);
            }
    }//GEN-LAST:event_eliminarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       abrejtree();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainlab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainlab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainlab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainlab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainlab5().setVisible(true);
            }
        });
    }

    private void abrejug() {
        jd_jugadores.setModal(true);
        jd_jugadores.pack();
        jd_jugadores.setLocationRelativeTo(this);
        jd_jugadores.setVisible(true);
    }

    private void abreen() {
        jd_entrenadores.setModal(true);
        jd_entrenadores.pack();
        jd_entrenadores.setLocationRelativeTo(this);
        jd_entrenadores.setVisible(true);
    }

    private void abrepre() {
        jd_preparadores.setModal(true);
        jd_preparadores.pack();
        jd_preparadores.setLocationRelativeTo(this);
        jd_preparadores.setVisible(true);
    }

    private void abreps() {
        jd_psicologos.setModal(true);
        jd_psicologos.pack();
        jd_psicologos.setLocationRelativeTo(this);
        jd_psicologos.setVisible(true);
    }

    private void abreagregar() {
        jd_agregar.setModal(true);
        jd_agregar.pack();
        jd_agregar.setLocationRelativeTo(this);
        jd_agregar.setVisible(true);
    }

    private void abrejl() {
        jlist.setModal(true);
        jlist.pack();
        jlist.setLocationRelativeTo(this);
        jlist.setVisible(true);
    }
    private void abrejtree() {
        jtree.setModal(true);
        jtree.pack();
        jtree.setLocationRelativeTo(this);
        jtree.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JRadioButton be;
    private javax.swing.JRadioButton bj;
    private javax.swing.JRadioButton bp;
    private javax.swing.JRadioButton bps;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField eanosc;
    private javax.swing.JTextField eapellido;
    private javax.swing.JTextField ecantcopas;
    private javax.swing.JTextField eedad;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JTextField enacionalidad;
    private javax.swing.JTextField enombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree;
    private javax.swing.JTextField janos;
    private javax.swing.JTextField japellido;
    private javax.swing.JTextField jcantp;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JDialog jd_entrenadores;
    private javax.swing.JDialog jd_jugadores;
    private javax.swing.JDialog jd_preparadores;
    private javax.swing.JDialog jd_psicologos;
    private javax.swing.JTextField jedad;
    private javax.swing.JList<String> jl_personas;
    private javax.swing.JDialog jlist;
    private javax.swing.JTextField jnacionalidad;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jnumerojug;
    private javax.swing.JDialog jtree;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JTextField panosc;
    private javax.swing.JTextField papellido;
    private javax.swing.JTextField pedad;
    private javax.swing.JTextField pespecialidad;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pnacionalidad;
    private javax.swing.JTextField pnombre;
    private javax.swing.JPopupMenu popupjl;
    private javax.swing.JTextField psapellido;
    private javax.swing.JTextField psatendidos;
    private javax.swing.JTextField psedad;
    private javax.swing.JTextField psespecialidad;
    private javax.swing.JTextField psid;
    private javax.swing.JTextField psinformes;
    private javax.swing.JTextField psnacionalidad;
    private javax.swing.JTextField psnombre;
    private javax.swing.JTextField pstitulo;
    // End of variables declaration//GEN-END:variables
}
